<?php
// $Id: my_formcompleter.module
/**
* Implementation of hook_form_alter().
*
* This lets you make changes to any form in the site. You can alter, remove
* or add form elements. You can also alter the validation and submission
* behavior. The name will always be modulename_form_alter.
*/

function my_formcompleter_menu() {
  $items['data/dispensaries/autocomplete'] = array(
    'title' => 'Autocomplete Dispensaries',
    'page callback' => 'data_dispensaries_autocomplete',
    'access' => TRUE,
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['data/strains/autocomplete'] = array(
    'title' => 'Autocomplete Strains',
    'page callback' => 'data_strains_autocomplete',
    'access' => TRUE,
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
    
  return $items;
}

//////// Here's where we alter individual forms based on some regex matching

function my_formcompleter_form_alter(&$form, &$form_state, $form_id) {

if( ereg('views-exposed-form-dispensaries', $form['#id'])) {
  $form['name'] = array(
    '#type' => 'textfield',
    '#default_value' => $typed_string,
    '#size' => 20,
    '#maxlength' => 100
  );
 
   $form['city']['#size'] = '15';
   $form['postal_code']['#size'] = '10';
   $form['province']['#size'] = '10';

 }
 

if( ereg('views-exposed-form-samples', $form['#id'])) {
 
   $form['title'] = array(
    '#type' => 'textfield',
    '#default_value' => $typed_string,
    '#size' => 20,
    '#maxlength' => 100
   ); 
     
  $form['strain'] = array(
    '#type' => 'textfield',
    '#default_value' => $typed_string,
    '#size' => 20,
    '#maxlength' => 100,
    '#autocomplete_path' => 'data/strains/autocomplete'
  );
  
   $form['city']['#size'] = '15';
   $form['postal_code']['#size'] = '10';
   $form['province']['#size'] = '10';

 }
 
 if( ereg('views-exposed-form-strains', $form['#id'])) {
  $form['strain'] = array(
    '#type' => 'textfield',
    '#default_value' => $typed_string,
    '#size' => 60,
    '#maxlength' => 100,
    '#autocomplete_path' => 'data/strains/autocomplete'
  );
 
 }
 
}

//////// The query for the dispensaries autocomplete

function data_dispensaries_autocomplete($string='') {
$matches = array();
if ($string) {
$result = db_query_range("SELECT title FROM {node} WHERE type = 'dispensary' AND LOWER(title) LIKE LOWER('%s%')",$string,0,10);
while ($data = db_fetch_object($result)) {
$matches[$data->title] = check_plain($data->title);

}
}
print drupal_to_js($matches);
exit();

}

//////// The query for the strains autocomplete

function data_strains_autocomplete($string='') {
$matches = array();
if ($string) {
$result = db_query_range("SELECT title FROM {node} WHERE type = 'strain' AND LOWER(title) LIKE LOWER('%%%s%%')",$string,0,10);
while ($data = db_fetch_object($result)) {
$matches[$data->title] = check_plain($data->title);

}
}
print drupal_to_js($matches);
exit();

}
